add_friend/urls.py
from django.conf.urls import url
from .views import index,add_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend'),
]

halprofil/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

tugas1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView
import halprofil.urls as halprofil
import update_status.urls as update_status
import add_friend.urls as add_friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(halprofil,namespace='profile')),
	url(r'^status/', include(update_status,namespace='status')),
	url(r'^friends/', include(add_friend, namespace='add_friend')),
	url(r'^$', RedirectView.as_view(url='status/', permanent = True), name='index')
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    ]

add_friend/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
	name = models.CharField(max_length=27)
	url = models.URLField()
	created_date = models.DateTimeField(auto_now_add=True)

halprofil/models.py
from django.db import models

# Create your models here.

class DataProfile(models.Model):
	nama = models.CharField(max_length = 50)
	birthday = models.CharField(max_length = 50)
	gender = models.CharField(max_length = 50)
	expertise = models.TextField(max_length = 50)
	description = models.CharField(max_length = 50)
	email = models.CharField(max_length = 50)
	

update_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.TextField(max_length=140)
    date = models.DateTimeField(auto_now_add=True)

add_friend/forms.py
from django import forms

class Friend_Form(forms.Form):

    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan url herokuapp',
   }
    name_attrs = {
        'class': 'form-control',
        'placeholder':'Your friend\'s name'
    }

    url_attrs = {
        'class': 'form-control',
        'placeholder':'Your friend\'s url'
    }
    
    name = forms.CharField(label='Name',required=True, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label="URL",required=True, widget=forms.URLInput(attrs=url_attrs))

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Please tell us what are you thinking',
    }
    status_attrs = {
        'type': 'text',
        'cols': 180,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'What are you thinking...'
    }

    status_form = forms.CharField(label='', required=True, max_length=140, widget=forms.Textarea(attrs=status_attrs))

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

# Create your views here.
response = {}
def index(request):
	response['friend_form'] = Friend_Form
	response['friend'] = Friend.objects.all()
	html = 'friend_list/friend_list.html'
	return render(request, html, response)
	
def add_friend(request):
	form = Friend_Form(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name']
		response['url'] = request.POST['url']
		friend = Friend(name=form.cleaned_data['name'], url=form.cleaned_data['url'])
		friend.save()
	else:
		response['form'] = form
		
	html = 'friend_list/friend_list.html'
	response['friend'] = Friend.objects.all()
	return render(request, html, response)

halprofil/views.py
from django.shortcuts import render
from .models import DataProfile

name = 'Hepzibah Smith'
birth = '01 Jan'
gender = 'Female'
expertise = 'Marketing | Collector | Public Speaking'
description = 'Antique expert. Experience as marketer for 10 years'
email = 'hello@smith.com'
profile = DataProfile(nama = name, birthday = birth, gender = gender, expertise = expertise, description = description, email = email)

def index(request):
    response = {'name' : profile.nama, 'birthday' : profile.birthday, 'gender' : profile.gender, 'expertise' : profile.expertise, 'description' : profile.description, 'email' : profile.email}
    return render(request, 'halprofil/hal_profil.html', response)

update_status/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from datetime import datetime
from .forms import Status_Form
from .models import Status
from halprofil.views import name

# Create your views here.
status_dict = {}

def index(request):    
    status_dict['author'] = name
    status = Status.objects.all()
    status_dict['status'] = status
    html = 'update_status/update_status.html'
    status_dict['status_form'] = Status_Form
    return render(request, html, status_dict)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        status_dict['status_form'] = request.POST['status_form']
        status = Status(status=status_dict['status_form'])
        status.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

add_friend/templates/friend_list/friend_list.html
{% extends "friend_list/layout/base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Friends</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />
</head>
<body class="friend-body">
</section>
<hr/>
<<section name="input-friend" id="input-friend">
    <div class="container">
        <form id="form" method="POST" action="{% url 'add_friend:add_friend' %}">
            <h2>Add Friend</h2>
            {% csrf_token %}
            {{ friend_form }}
            <br>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Add Friend">
        </form>
    </div>
</section>

<section name="friend" id="friend">
    <div class="container">
    <br>
    <hr style="color: #d2ff7f">
    <h2 class="friend-title">Friends</h2>
    <hr style="color: #d2ff7f">
    <br>
      <div class="card-body">
        {% for i in friend %}
            <div class="card" style="width: 20rem;">
            <center><img class="card-img-top" src="{% static 'images/friend_icon.png' %}" alt="Card image cap" style="width: 100px; height: 100px;"></center>
            <center><h4 id="name-friend">{{i.name}}</h4></center>
            <center><p class="added-friend"> Added on {{i.created_date}}</p></center>
            <center><a href="{{ i.url }}"> {{i.url}} </a></td></center>
            <br>
          </div>
        {% endfor %}
      </div>
    </div>
</section>

<!-- Print errors if any -->
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <!-- List all previous status -->
    <div class="container stasuses">
        {% for i in status reversed %}
            <div class="flex-item">
                <h5> {{ i.user.name }} </h5>
                {{ i.friend }} <br/>
                <sub> {{ i.date }} </sub>
            </div>
        {% endfor %}
    </div>
</body>
{% endblock %}

add_friend/templates/friend_list/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Tugas 1 PPW">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        {% block title %}Home{% endblock %}
    </title>
    <style>
    body{
        background: #15384f;
    }
    </style>
</head>
<body>
    <div class="background">
        <header>
            {% include "halprofil/partials/header.html" %}
        </header>
        <content>
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>

        </content>
        <footer>
            {% block footer %}
            {% include "halprofil/partials/footer.html" %}
            {% endblock %}
        </footer>

        <!-- Jquery n Bootstrap Script -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </div>
</body>

add_friend/templates/friend_list/partials/footer.html
</br>
<center><p style = "color:  #caccde" > Made with love by &copy; Kelompok 6 </p></center>

add_friend/templates/friend_list/partials/header.html
<style>
  .navbar-static-top {
    background-color: white;
    position: fixed;
    margin-bottom: 19px;
  }
  .navbar-default .navbar-nav>li>a {
    cursor: pointer;
  }
</style>

<nav style="background-color: #f3eff0" class = "navbar-fixed-top navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-move" href='/status/'>Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a class = "navbar-move" href='/profile/'>Profile</a></li>
        <li><a class = "navbar-move" href='/friends/'>Friends</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

halprofil/templates/halprofil/hal_profil.html
<!DOCTYPE html>
{% extends "halprofil/layout/base.html" %}
{% block content %}

<style>
	.grow{
		 transition: all .3s ease-in-out;
	}
	.grow:hover{
		 transform: scale(1.1); 
	}
</style>

<body style = "margin-top : 70px">
	<h1 style="color: #caccde ">Profile</h1>

	<img class = "img-responsive center-block grow grow:hover" style="border-radius : 50%" src="https://koreaboo.global.ssl.fastly.net/wp-content/uploads/2017/06/WBB-texting.jpg" alt="myself" height="150px" width="150px">

	</br>

	<h2 style="color:  #caccde" align ="center">{{name}}</h2>

	</br>

	<table class = "center-block" style=" width:35% ; margin : 0px auto">
		<style>
			table, th, td{
				text-align: center;
				color:  #caccde 
			}
			th{
				height: 35px;
				width:30%;
			}
			td{
				height: 35px;
			}
			tr:hover{
				background-color:  #7a7ea2 ;
				height: 50px;
			}
		</style>
		<tr class = "grow grow:hover">
			<th>Birthday</th>
			<td>{{birthday}}</td>
		</tr>
		<tr class = "grow grow:hover">
			<th>Gender</th>
			<td>{{gender}}</td>
		</tr>
		<tr class = "grow grow:hover">
			<th>Expertise</th>
			<td>{{expertise}}</td>
		</tr>
		<tr class = "grow grow:hover">
			<th>Description</th>
			<td>{{description}}</td>
		</tr>
		<tr class = "grow grow:hover">
			<th>Email</th>
			<td>{{email}}</td>
		</tr>
	</table>




	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	 <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	 </script>
</body>

{% endblock %}

halprofil/templates/halprofil/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Tugas 1 PPW">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        {% block title %}Home{% endblock %}
    </title>
    <style>
    body{
        background: #15384f;
    }
    </style>
</head>
<body>
    <div class="background">
        <header>
            {% include "halprofil/partials/header.html" %}
        </header>
        <content>
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>

        </content>
        <footer>
            {% block footer %}
            {% include "halprofil/partials/footer.html" %}
            {% endblock %}
        </footer>

        <!-- Jquery n Bootstrap Script -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </div>
</body>

halprofil/templates/halprofil/partials/footer.html
</br>
<center><p style = "color:  #caccde" > Made with love by &copy; Kelompok 6 </p></center>

halprofil/templates/halprofil/partials/header.html
<style>
  .navbar-static-top {
    background-color: white;
    position: fixed;
    margin-bottom: 19px;
  }
  .navbar-default .navbar-nav>li>a {
    cursor: pointer;
  }
</style>

<nav style="background-color: #f3eff0" class = "navbar-fixed-top navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-move" href='/status/'>Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a class = "navbar-move" href='/profile/'>Profile</a></li>
        <li><a class = "navbar-move" href='/friends/'>Friends</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

templates/base.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="en">
<body style="background-color :  #450a21">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/friends/">Friends</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/profile/">Profile</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
</body>

update_status/templates/update_status/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Tugas 1 PPW">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

	{% block style %}
	<!-- css -->
	{% endblock %}
	
    <title> 
        {% block title %}Home{% endblock %}
    </title>
    <style>
    body{
        background: #15384f;
    }
    </style>
</head>
<body>
    <div class="background">
        <header>
            {% include "update_status/partials/header.html" %}
        </header>
        <content>
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>

        </content>
        <footer>
            {% block footer %}
            {% include "update_status/partials/footer.html" %}
            {% endblock %}
        </footer>

        <!-- Jquery n Bootstrap Script -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </div>
</body>

update_status/templates/update_status/partials/footer.html
</br>
<center><p style = "color:  #caccde" > Made with love by &copy; Kelompok 6 </p></center>

update_status/templates/update_status/partials/header.html
<style>
  .navbar-static-top {
    background-color: white;
    position: fixed;
    margin-bottom: 19px;
  }
  .navbar-default .navbar-nav>li>a {
    cursor: pointer;
  }
</style>

<nav style="background-color: #f3eff0" class = "navbar-fixed-top navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-move" href='/status/'>Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a class = "navbar-move" href='/profile/'>Profile</a></li>
        <li><a class = "navbar-move" href='/friends/'>Friends</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

update_status/templates/update_status/update_status.html
{% extends "update_status/layout/base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href={%static "/css/update_status.css" %}>
{% endblock %}

{% block content %}
<h1 class="main-title">STATUS</h1>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'status:add_status' %}">
            <h2 style="color:white;">Update Status</h2>
            {% csrf_token %}
            {{ status_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-primary pull-right btn-info" value="Post">
            <br>
        </form>
    </div>
</section>

<section name="my-list" id="my-list">
    <div class="container">
		<h2 class="page-header" style="color:white;">Status</h2>
		<div class="flex">
            {% if status %}
                {% for data in status reversed %}
				<figure class='thumbnail'>
					<table>
						<tr>
							<td>
								<h3>Hepzibah Smith</h3>
								<img class = "scaled" align="top-left" style="border-radius : 50%" src="https://koreaboo.global.ssl.fastly.net/wp-content/uploads/2017/06/WBB-texting.jpg" alt="myself" height="150px" width="150px">					
							</td>
							<td>
								<div class="flex-item">
									<div class="to-do-list">
										<div class="to-do-list-status">
											{{data.status}}
										</div>
										<div class="to-do-list-date-added">
											{{data.date}}
										</div>
									</div>
								</div>
							</td>
						</tr>
					</table>
				</figure>
                {% endfor %}
            {% else %}
			<figure class='thumbnail'>
            <div class="alert text-center">
                Belum ada status.
            </div>
			</figure>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}